---
title: "Evaluation_5"
author: "Christiane"
date: "`r format(Sys.Date())`"
output: github_document
---

1. Créer une série temporelle du CO2 à partir des données de hawai.csv.
2. Séparer la série en parties d'entraînement (environ 70% des données) et en partie test.
3. Créer un modèle ETS sur les données d'entraînement, puis projeter la prévision de CO2 atmosphérique pour comparer aux données test.
4. Effectuer une analyse des résidus.
Commenter: le modèle est-il fiable? Comment pourrait-il être amélioré?
Selon le Test Ljung_box la série temporelle n'a pas été générée à partir d'un bruit blanc (valeur de la p-value faible) et les résidus ne sont pas correlés donc pas dérivés d'un bruit blanc et donc il faudrait tester un autre modèle.

Vous devez me remettre un lien vers un répertoire git de votre choix (GitHub, GitLab, etc.) comprenant un code reproductible de votre démarche en format R-markdown. 

[Evaluation5_Christiane]("https://github.com/chtdelia/evaluation5/blob/master/Christiane_git.Rmd")

```{r}
library(tidyverse)
library(lubridate)
library(forecast)
library(fpp2)
library(agridat)
library(expsmooth)


setwd("C:/Users/Utilisateur/Dropbox/Analyse") 
hawai <- readr::read_csv("CodeR/_Evaluation5/hawai.csv")
ggplot(data = hawai, mapping = aes(x = time, y = CO2)) +
  geom_line() 
 
hawai_ts <- ts(hawai %>% select(-time),
           start = c(hawai$time[3] %>% time(), 1),
           frequency = 12)

ggplot(data = hawai, mapping = aes(x = time, y = CO2)) +
  geom_line(colour ="red", lwd=0.7) + 
  scale_x_continuous(breaks=c(1958:2001)) +
  theme(axis.text=element_text(colour="black", angle=45, hjust=1.1))
  
hawai_ts_train <- window(hawai_ts, start = 1, end = 30)
hawai_ts_test <- window(hawai_ts, start = 31)

hm_naive <- snaive(hawai_ts_train, h = 44)
autoplot(hm_naive) +
  forecast::autolayer(fitted(hm_naive)) +
  forecast::autolayer(hawai_ts_test, color = rgb(0, 0, 0, 0.6)) +
  labs(x = "Time", y = "CO2")
  
hawai_model <- ets(hawai_ts_train) 
hawai_model

autoplot(hawai_model)

hawai_ets <- hawai_ts_train %>% ets()
hawai_fc <- hawai_ets %>% forecast()
hawai_fc %>% autoplot()

checkresiduals(hawai_ets) 
  
```

